---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: am2g-itopsprod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: am2g
  template:
    metadata:
      labels:
        app: am2g
    spec:
      containers:
      - name: am2g-pod
        image: mrfrace/am2g:latest
        ports:
          - containerPort: 8000
      env:
        - name: TENANT_ID
          valueFrom:
            secretKeyRef:
              name: tenantid
              key: key1
        - name: CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: clientid
              key: key1
        - name: CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: clientsecret
              key: key1
        - name: SUBSCRIPTION_ID
          valueFrom:
            secretKeyRef:
              name: sbscriptionid
              key: key1
      restartPolicy: Always




